# -*- coding: utf-8 -*-
"""solution.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12KkG7xRCSSp8qU0bbvAdp25LgGZBTJNz
"""

import numpy as np
import sys
from helper import *
from PIL import Image
import matplotlib.image
def show_images(data):
    """Show the input images and save them.

    Args:
        data: A stack of two images from train data with shape (2, 16, 16).
              Each of the image has the shape (16, 16)

    Returns:
        Do not return any arguments. Save the plots to 'image_1.*' and 'image_2.*' and
        include them in your report
    """
    ### YOUR CODE HERE
    matplotlib.image.imsave('image_1.png', data[0,:,:])
    matplotlib.image.imsave('image_2.png', data[1,:,:])
    ## END YOUR CODE


def show_features(X, y, save=True):
    """Plot a 2-D scatter plot in the feature space and save it. 

    Args:
        X: An array of shape [n_samples, n_features].
        y: An array of shape [n_samples,]. Only contains 1 or -1.
        save: Boolean. The function will save the figure only if save is True.

    Returns:
        Do not return any arguments. Save the plot to 'train_features.*' and include it
        in your report.
    """
    ### YOUR CODE HERE
    for i in range (len(y)-1):
      if y[i]==1 :
        plt.scatter(X[i,0], X[i,1],marker='*',c='red')
      else: 
        plt.scatter(X[i,0], X[i,1],marker='+',c='blue')
      
    if save:
      plt.savefig('books_readtrain_features.png')
    ### END YOUR CODE


class Perceptron(object):
    
    def __init__(self, max_iter):
        self.max_iter = max_iter
        #w = [0,1,1]
        self.W = np.zeros(3)

    def predict (self,X):
        """Predict class labels for samples in X.

        Args:
            X: An array of shape [n_samples, n_features].

        Returns:
            preds: An array of shape [n_samples,]. Only contains 1 or -1.
        """
        ### YOUR CODE HERE
        result = np.dot(X,self.W)
        if result >0:
          group=1        
        else:
          group=-1
        
        return group
          
        ### END YOUR CODE

    def fit(self, X, y):
        """Train perceptron model on data (X,y).

        Args:
            X: An array of shape [n_samples, n_features].
            y: An array of shape [n_samples,]. Only contains 1 or -1.

        Returns:
            self: Returns an instance of self.
        """
        ### YOUR CODE HERE
        for _ in range(self.max_iter):
            for input, label in zip(X, y):
                y_cap = self.predict(input)
                self.W += 0.01*(label - y_cap) * input

        # After implementation, assign your weights w to self as below:
        # self.W = w
        
        ### END YOUR CODE
        
        return self

    def get_params(self):
        """Get parameters for this perceptron model.

        Returns:
            W: An array of shape [n_features,].
        """
        if self.W is None:
            print("Run fit first!")
            sys.exit(-1)
        return self.W


    def score(self, X, y):
        """Returns the mean accuracy on the given test data and labels.

        Args:
            X: An array of shape [n_samples, n_features].
            y: An array of shape [n_samples,]. Only contains 1 or -1.

        Returns:
            score: An float. Mean accuracy of self.predict(X) wrt. y.
        """
        ### YOUR CODE HERE
        count =0;
        for i in range (len(y)-1):
          result = np.dot(X[i], self.W)
          if result >0 and y[i]==1:
            count =count+1
          elif result <0 and y[i]==-1:
            count =count+1        
        return count/len(y)
        ### END YOUR CODE




def show_result(X, y, W):
    """Plot the linear model after training. 
       You can call show_features with 'save' being False for convenience.

    Args:
        X: An array of shape [n_samples, 2].
        y: An array of shape [n_samples,]. Only contains 1 or -1.
        W: An array of shape [n_features,].
    
    Returns:
        Do not return any arguments. Save the plot to 'result.*' and include it
        in your report.
    """
    ### YOUR CODE HERE
    for i in range (len(y)-1):
      if y[i]==1 :
        plt.scatter(X[i,0], X[i,1],marker='*',c='red')
      else: 
        plt.scatter(X[i,0], X[i,1],marker='+',c='blue')
    x_ticks = np.linspace(-0.4, -0.2, 1000)
    y_ticks = -x_ticks*(W[1]/W[2])-(W[0]/W[2])
    plt.plot(x_ticks, y_ticks)
    plt.savefig('result.png')
    ### END YOUR CODE



def test_perceptron(max_iter, X_train, y_train, X_test, y_test):

    # train perceptron
    model = Perceptron(max_iter)
    model.fit(X_train, y_train)
    train_acc = model.score(X_train, y_train)
    W = model.get_params()

    # test perceptron model
    test_acc = model.score(X_test, y_test)

    return W, train_acc, test_acc